# 标量

In [1]:
import torch

In [2]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

# 向量

In [3]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
x[3]

tensor(3)

In [5]:
# 长度
len(x)

4

In [14]:
# 维度和形状
x.dim(),x.shape

(1, torch.Size([4]))

# 矩阵

In [8]:
a = torch.arange(20).reshape((5,4))
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [9]:
# 转置
a.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [10]:
len(a)

5

In [15]:
a.dim(),a.shape

(2, torch.Size([5, 4]))

# 张量

In [16]:
x = torch.arange(24).reshape(2,3,4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [19]:
# 点乘，哈达玛积：对应位置相乘
b = a.clone()
a * b

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225],
        [256, 289, 324, 361]])

In [20]:
torch.mul(a,b)

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225],
        [256, 289, 324, 361]])

In [21]:
# 叉乘 矩阵乘法
torch.mm(a,b.T)

tensor([[  14,   38,   62,   86,  110],
        [  38,  126,  214,  302,  390],
        [  62,  214,  366,  518,  670],
        [  86,  302,  518,  734,  950],
        [ 110,  390,  670,  950, 1230]])

# 点积

In [31]:
x = torch.arange(4,dtype=torch.float32)
y = torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [32]:
torch.sum(x * y)

tensor(6.)

# sum

In [22]:
x = torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [23]:
a.shape,a.sum()

(torch.Size([5, 4]), tensor(190))

In [28]:
a.sum(axis=0).shape

torch.Size([4])

In [29]:
a.sum(axis=1).shape

torch.Size([5])

In [27]:
a.sum(axis=0,keepdim=True).shape

torch.Size([1, 4])

In [30]:
a.sum(axis=1,keepdim=True)

tensor([[ 6],
        [22],
        [38],
        [54],
        [70]])

# 范数

In [33]:
# L1范数 向量元素绝对值之和
u = torch.tensor([3.0,-4.0])
torch.abs(u).sum()

tensor(7.)

In [34]:
# L2范数 向量元素平方和的平方根
torch.norm(u)

tensor(5.)

In [35]:
# 矩阵的F范数(佛罗贝尼乌斯范数)，矩阵元素的平方和的平方根
torch.norm(torch.ones((4,9)))

tensor(6.)